language: objective-c
osx_image: xcode9.1
script:
  - xcodebuild -scheme LeakFinder -workspace LeakFinder.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.1' build test
